version: '2'
services:



  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    ports:
      - 8000:80
    links:
      - app
    restart: always

   # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"

  # The Database
  mysql:
    image: mysql:5.6
    environment:
        - "MYSQL_DATABASE=laravel"
        - "MYSQL_USER=laravel"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_ROOT_PASSWORD=secret"
    ports:
          - "33061:3306"

